{
 "title": "Room Monitor",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Air Quality",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT airquality FROM continuosRoomData LIMIT 50"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT humi FROM continuosroomdata LIMIT 50 "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date FROM chronicalroomdata"
    },
    {
     "rawSql": "SELECT temp FROM chronicalroomdata"
    }
   ]
  },
  {
   "title": "Temperature Title",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temp FROM continuosroomdata LIMIT 50 "
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT date FROM chronicalroomdata"
    },
    {
     "rawSql": "SELECT humi FROM chronicalroomdata"
    }
   ]
  },
  {
   "title": "Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * FROM continuosroomdata LIMIT 50 "
    }
   ]
  },
  {
   "title": "Air Quality",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT date FROM chronicalroomdata"
    },
    {
     "rawSql": "SELECT airQuality FROM chronicalroomdata"
    }
   ]
  }
 ]
}